using System.Text;
using System.Text.Json;

namespace PdfmeCore;

public static class ReportValuesClassGenerator
{
    public static string GetOutputPath(string layoutPath)
    {
        var fullPath = Path.GetFullPath(layoutPath);
        var fileName = Path.GetFileName(fullPath);
        var stem = fileName.EndsWith(".layout.json", StringComparison.OrdinalIgnoreCase)
            ? fileName[..^".layout.json".Length]
            : Path.GetFileNameWithoutExtension(fileName);
        return Path.Combine(Path.GetDirectoryName(fullPath)!, stem + ".Values.cs");
    }

    public static void Write(LayoutDocument layout, string layoutPath)
    {
        LayoutValidator.Validate(layout, requireReportName: true);
        File.WriteAllText(GetOutputPath(layoutPath), Generate(layout), new UTF8Encoding(false));
    }

    public static string Generate(LayoutDocument layout)
    {
        LayoutValidator.Validate(layout, requireReportName: true);
        var className = ToIdentifier(layout.ReportName, "Report") + "Values";
        var propertyNames = new HashSet<string>(StringComparer.Ordinal) { className };
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        source.AppendLine("using System.Text.Json.Serialization;");
        source.AppendLine();
        source.AppendLine("namespace PdfmeReports;");
        source.AppendLine();
        source.AppendLine($"public sealed class @{className}");
        source.AppendLine("{");
        foreach (var field in layout.Fields)
        {
            var name = ToPascalIdentifier(field.Name);
            var uniqueName = name;
            for (var index = 2; !propertyNames.Add(uniqueName); index++)
                uniqueName = $"{name}_{index}";
            source.AppendLine($"    [JsonPropertyName({JsonSerializer.Serialize(field.Name)})]");
            source.AppendLine($"    public string @{uniqueName} {{ get; set; }} = string.Empty;");
            source.AppendLine();
        }
        source.AppendLine("}");
        return source.ToString();
    }

    private static string ToIdentifier(string value, string fallback)
    {
        var result = new StringBuilder();
        foreach (var character in value.Trim())
            result.Append(char.IsLetterOrDigit(character) || character == '_' ? character : '_');
        if (result.Length == 0) return fallback;
        if (!char.IsLetter(result[0]) && result[0] != '_') result.Insert(0, '_');
        return result.ToString();
    }

    private static string ToPascalIdentifier(string value)
    {
        var identifier = ToIdentifier(value, "Field");
        return char.ToUpperInvariant(identifier[0]) + identifier[1..];
    }
}

