// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace PdfmeReports;

public sealed class @現品票テストValues
{
    [JsonPropertyName("partNo")]
    public string @PartNo { get; set; } = string.Empty;

    [JsonPropertyName("lot")]
    public string @Lot { get; set; } = string.Empty;

    [JsonPropertyName("qr")]
    public string @Qr { get; set; } = string.Empty;

    [JsonPropertyName("barcode")]
    public string @Barcode { get; set; } = string.Empty;

}
